import PostPage from "../../components/post/index"

export const metadata = {
    title: "Portfolio | Posts",
    description: "Generated by create next app",
  };
const Post=()=>
{
   return(
    <PostPage />
   )
}
export default Post;