import ContactPage from "../../components/contact/index"

export const metadata = {
  title: "Portfolio | Contact",
  description: "Generated by create next app",
};

const Contact = () => {
 return(
    <ContactPage />
 )
};

export default Contact;
