import About from "../../components/about/index"

export const metadata = {
  title: "Portfolio | About",
  description: "Generated by create next app",
};

const  Resume=()=> {
  return(
     <About />
  );
  }
  
export default Resume;