import LiveProject from "../../components/project/index"


export const metadata = {
  title: "Portfolio | Projects",
  description: "Generated by create next app",
};

const  Work=()=> {
 return(
  <LiveProject />
 )
  }
  
  export default Work;