// app/not-found.js
import PageNotFound from "../components/notFound/index"
export const metadata = {
  title: "Portfolio | Not Found",
  description: "Generated by create next app", 
};

export default function NotFound() {
  return (
    <PageNotFound />
  );
}
