import HomePage from '../components/home/index'
export const metadata = {
  title: "Portfolio | Home",
  description: "Generated by create next app", 
};
const Home = () => {
  return(
   <HomePage/>
  );
};

 export default Home;
