import HireMe from "../../components/hireme/index"

export const metadata = {
    title: "Portfolio | Hire",
    description: "Generated by create next app",
  };
const Hireme=()=>
{
   return(
    <HireMe />
   )
}
export default Hireme;